#!/bin/sh

#./runner --pwd="$(pwd)" --config=config.yaml --results=results/results.json
#bazel run @stargrade//:runner -- --pwd="$(pwd)" --config=config.yaml --results=results/results.json
starrun --pwd="$(pwd)" --config=config.yaml --results=results/results.json
