cc_binary(
    name = "tests",
    srcs = ["tests.cc"],
    deps = [
        "//submission",
        "@abseil//absl/flags:flag",
        "@abseil//absl/flags:parse",
        "@stargrade//stargrade/gtest:gradescope_test_listener",
    ],
)
